# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-21 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hId',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
