# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theSink', '0002_remove_user_hashid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hashId',
            field=models.CharField(default='abracadabraB', max_length=255),
        ),
    ]
