# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theSink', '0003_user_hashid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(default="I'm hungry", verbose_name=1000)),
                ('ingr', models.TextField(default="I'm hungry", verbose_name=1000)),
                ('inst', models.TextField(default="I'm hungry", verbose_name=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRecipes', to='theSink.User')),
            ],
        ),
    ]
