# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theSink', '0006_auto_20180919_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='userid',
        ),
    ]
