# Generated by Django 2.1 on 2018-09-20 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theSink', '0007_auto_20180919_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message_id',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
