# Generated by Django 2.1 on 2018-09-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theSink', '0009_auto_20180919_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='used',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='message_id',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
