# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_hid'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='book_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookReviews', to='books.Book'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userReviews', to='login.User'),
        ),
    ]
