# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-22 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180922_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
