# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='vId',
        ),
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.TextField(default='No description provided.', verbose_name=1000),
        ),
        migrations.AddField(
            model_name='item',
            name='itemPrice',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='priceItems', to='amadon.Price'),
        ),
    ]
