# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0002_auto_20180920_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='numItems',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
