# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0003_auto_20180920_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemPrice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='money',
        ),
        migrations.RemoveField(
            model_name='user',
            name='numItems',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='vId',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
