# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0004_auto_20180920_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=False),
        ),
    ]
