# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0005_auto_20180920_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(to='amadon.User'),
        ),
    ]
