# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0006_auto_20180920_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(related_name='items', to='amadon.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vId',
            field=models.CharField(max_length=255),
        ),
    ]
