# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-20 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amadon', '0007_auto_20180920_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='users',
        ),
        migrations.AddField(
            model_name='purchase',
            name='itemId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_item', to='amadon.Item'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_purchases', to='amadon.User'),
        ),
    ]
